### ISSUE TITLE
Hex package includes a file not present in git repo, crashes app not using prometheus

### ISSUE THREAD

**Issue by samsondav** [soundtrackyourbrand/absinthe-metrics#2]
In the hex package there is a backend called "prometheus_label_histogram".

This weirdly does not show up in the git repo.

It fails to compile if the user does not have prometheus installed.

**Comment by frekw** [comment]
Whoops, seems like I managed to push a Hex release with a dirty working copy. Sorry!

0.7.0 fixes it.
